### ISSUE TITLE
Reftime

### ISSUE THREAD

**Issue by hursey013** [andrefelipe/orchestrate-php#1]
Great client you have developed, I'm currently using it in my project.  Question - is there any way to retrieve the refTime for a key value?  It seems to be omitted from all of the responses unless I'm missing it somehow.  Thanks again for all your work on this!

**Comment by andrefelipe** [comment]
Hi Hursey, thanks for the feedback, I am glad that you found the client useful.

You can use the "getReftime" method, like $myItem->getReftime(). Although please note that Orchestrate does not return the reftime in regular KeyValue GET requests, only on Refs or Search requests.

You could work like this:
$refs = $myItem->refs();
$refs->get(10);
print_r($refs[0]->getReftime());

Let me know if I can help you further.

Best regards.
